<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testng-results failed="2" passed="5" skipped="0" total="7">
    <suite duration-ms="4729" name="io.cucumber.core.plugin.TestNGFormatter">
        <test duration-ms="4729" name="io.cucumber.core.plugin.TestNGFormatter">
            <class name="To check the functionality for creation of new user">
                <test-method duration-ms="1980" finished-at="2022-05-05T12:38:31.325077800Z" name="Create new user" started-at="2022-05-05T12:38:29.299557900Z" status="PASS"/>
            </class>
            <class name="To retrieve the data for particular user using ID">
                <test-method duration-ms="526" finished-at="2022-05-05T12:38:31.875828100Z" name="Get user detail with the help of his/her ID" started-at="2022-05-05T12:38:31.344493200Z" status="FAIL">
                    <exception class="java.lang.AssertionError">
                        <message><![CDATA[Given Navigate to the home page.............................................passed
When Provide the ID of the user.............................................passed
Then Validate positive response code and output.............................failed
]]></message>
                        <full-stacktrace><![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at stepDefinition.StepDefinition02.validate_positive_response_code(StepDefinition02.java:73)
	at ✽.Validate positive response code and output(file:///C:/Users/yashika.agrawal/Documents/workspace/com.api.selenium/src/test/resources/Features/login2.feature:11)
]]></full-stacktrace>
                    </exception>
                </test-method>
            </class>
            <class name="To check and validate login functionality with positive response code received">
                <test-method duration-ms="468" finished-at="2022-05-05T12:38:32.358605200Z" name="Login with a positive set of credential" started-at="2022-05-05T12:38:31.887858200Z" status="PASS"/>
            </class>
            <class name="To retrieve and assert the data for particular user using ID">
                <test-method duration-ms="154" finished-at="2022-05-05T12:38:32.518128200Z" name="Get user detail with the help of his/her ID" started-at="2022-05-05T12:38:32.362392100Z" status="FAIL">
                    <exception class="java.lang.AssertionError">
                        <message><![CDATA[Given Navigate to the home page.............................................passed
When Provide the ID of the user.............................................passed
Then Validate positive response code and output.............................failed
]]></message>
                        <full-stacktrace><![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at stepDefinition.StepDefinition02.validate_positive_response_code(StepDefinition02.java:73)
	at ✽.Validate positive response code and output(file:///C:/Users/yashika.agrawal/Documents/workspace/com.api.selenium/src/test/resources/Features/login4.feature:11)
]]></full-stacktrace>
                    </exception>
                </test-method>
            </class>
            <class name="To check and validate the functionality when user is created">
                <test-method duration-ms="395" finished-at="2022-05-05T12:38:32.923075300Z" name="Foreign Exchange Page failure" started-at="2022-05-05T12:38:32.524387900Z" status="PASS"/>
            </class>
            <class name="To check and validate and assert the functionality when user is created">
                <test-method duration-ms="313" finished-at="2022-05-05T12:38:33.251034200Z" name="Foreign Exchange Page failure" started-at="2022-05-05T12:38:32.931647200Z" status="PASS"/>
            </class>
            <class name="Post with future date and validate">
                <test-method duration-ms="640" finished-at="2022-05-05T12:38:33.897222900Z" name="Foreign Exchange Page future date" started-at="2022-05-05T12:38:33.254024300Z" status="PASS"/>
            </class>
        </test>
    </suite>
</testng-results>
ssed
]]></system-out>
    </testcase>
</testsuite>
